language: ruby
cache:
- bundler
before_script:
deploy:
  provider: heroku
  api_key:
    secure: "LIXWeTLrJNsf1NbV9/THUu6ra9c4xq2Z9OVjUqzMSygoE8cg/YuInoqC5hKB0YhykybhTRhjYt0Bt5LTE8obuUVqIM2OMxc8C1uX3NYn2FYcG7kk7XZUY6mT5qUpas1bjNfDT95QZcpLwJ7Mcn/CSrKwdR1K4sP7YVWgm+qyrKjTF/Ms2S0eOsEubSf3Kj8ZsKFU0wMM69x4WIl7BfjDKqiT9HW5KuIk+KzKbUCIbZ7x0/XYlEAK83V2MdNLiHb+IIdgkV6iCTRhcooh/hmWUAL8Vxu8ZDZJjfcLTBcAlyeRcjwzreUQDRM8ZovW0otiVGu5yMndZpRCgKtv8JLvF2ar6oz10nahFyqJ+LEsSMZqUXLw1tJVZSKL4GsSeoLDAMSAw4wOk7WvTlntTu4THRdwNWDyGOmo5ikhu8N1a5+4hVy9iTubGglDN/+QAaoDzdFcIS5uVNKKr3kyzXRRfYfBKyf5NZNpwBuYmsnGBB47IIPXI7YMrWmFiysDIv1b6oc8dAVKJTiW5uMbaq5lY4T3HHoNM3J+qp3EDR+cKXm2VSb5pMrHljIbvDmDIxpIEN+h/CFnm/Imi2AkMt0vAs0diBmy4k+q9R17YdN9agOpxTTxF+D5uqOtHE6sDOnAQVTMFRcL5cLcg1BwrPVt8VP5tBtGctP7E173GK2bEfk="
  app: app-people-management
  on:
    repo: diegobassan/peopleManagement
  skip_cleanup: true
