development:
  adapter: postgresql
  encoding: unicode
  database: peopleManagement
  pool: 5
  username: vagrant
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: de89c9td0rjo3j
  pool: 5

production:
  adapter: postgresql
