default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: peopleManagement
  username: vagrant
  password: 123456

test:
  <<: *default
  database: peopleManagement_test
