development:
  adapter: postgresql
  encoding: unicode
  database: peopleManagement
  pool: 5
  username: vagrant
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: peopleManagement
  pool: 5
  username: cwppmjrcrqwokb
  password: 123456

production:
  adapter: postgresql
