development:
  adapter: postgresql
  encoding: unicode
  database: postgresql-elliptical-31692
  pool: 5
  username: bsn.diego@gmail.com
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: postgresql-elliptical-31692
  pool: 5
  username: bsn.diego@gmail.com
  password:
